env:
  global:
    - CC_TEST_REPORTER_ID=c0d55dbd983adac527dd447edd53e8ca9afdcb69db76968bef608644298b559f
language: ruby
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.4
  - 2.5
  - 2.6
